### ISSUE TITLE
Running Dashboard on Base4

### ISSUE THREAD

**Issue by obliviateandsurrender** [vlead/lab-data-service-dashboard#25]
I checked all of the proxy settings in the app and it seems fine to me. Can it be tried with the latest commit in the web-app branch? Furthermore, do keep in mind to fill in google oauth credentials along with adding the user logging in the database before hand. 
Post any errors codes/ success codes encountered. 
Ps. In the networks tab inside developer-options do check if loading of JavaScript and JSON file is initiated along with logged_in function call. Kindly report what happens so I can further cross check the issue asap.

**Comment by madhavipuliraju** [comment]
After the successful deployment of LDS Dashboard on base4, the following changes were made in the container:
1) Created OAuth Credentials on google developers console. 
2) Updated Client Id and Client Secret in in goauth_config.py file
3) Updated email id in mysql database
After login the page was throwing the following error:
{
  "message": "HTTP connectivity error", 
  "success": false
}
 In the networks tab inside developer-options, **401 unauthorized error** 
Same issue with Base1 as well.

**Comment by obliviateandsurrender** [comment]
I will try re-implementing the google oauth from scratch, let's see if that fixes the issue.

**Comment by madhavipuliraju** [comment]
Manually deployed this application on independent container in Base4:
IP Address: 10.4.14.237
URL: http://lds-dashboard-base4.vlabs.ac.in/
Found the following error log in log file:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2017-08-23 06:49:38,804: ERROR: api.py: loggedin():124: Failed to locate Google Token in session

**Comment by obliviateandsurrender** [comment]
I now have access to my ldap account. So can you tell me the steps to
deploy the app in it so that I can check and fix the problem regarding
fetching of token in the session?
Or if you are free maybe I could drop by tomorrow around 4?

**Comment by madhavipuliraju** [comment]
Also getting the following error:
2017-08-23 08:24:11,915: ERROR: app.py: log_exception():1560: Exception on /authorized [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/runtime/rest/app/users/api.py", line 71, in callback
    authorization_response=request.url)
  File "/usr/local/lib/python2.7/dist-packages/requests_oauthlib/oauth2_session.py", line 187, in fetch_token
    state=self._state)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/clients/web_application.py", line 174, in parse_request_uri_response
    response = parse_authorization_code_response(uri, state=state)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 218, in parse_authorization_code_response
    raise InsecureTransportError()
InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.

**Comment by madhavipuliraju** [comment]
Testing (base4) URL: [lds-dashboard-7.vlabs.ac.in](lds-dashboard-7.vlabs.ac.in)
